Releases version 1.0
angelicaameira/DateCounter pull request #18
Opened 2022-11-09 20:07 UTC by angelicaameira

2022-11-18 23:22 UTC, antoniogermano requested changes
Favor realizar as alterações solicitadas

2022-11-18 23:22 UTC, antoniogermano commented on EventIntents/IntentHandler.swift
> +        completion(.success(with: EventType(identifier: "ID", display: "Meu evento 1")))
Corrigir implementação, que está vazia/placeholder, e apagar códigos comentados

2022-11-18 23:22 UTC, antoniogermano commented on DateCounter/Views/ManageEventView.swift
> +
Remover quebra de linha desnecessária

2022-11-19 16:36 UTC, angelicaameira commented on DateCounter/Views/DetailView.swift
> +    private var toolbarContent: ToolbarItem<(), Button<Label<Text, Image>>> {
qual variável precisa ficar igual essa?

private var toolbarContent: ToolbarItem<(), Button<Label<Text, Image>>>

2022-11-19 16:49 UTC, angelicaameira commented on EventIntents/IntentHandler.swift
> +        completion(.success(with: EventType(identifier: "ID", display: "Meu evento 1")))
Não era você que pegou essa issue? Poderia implementa-la?

2022-11-19 16:52 UTC, angelicaameira commented on Widgets/Widgets.swift
> +        return event
Esses Widget são coisa de QuACK

2022-11-20 12:04 UTC, antoniogermano commented on DateCounter/DateCounter.xcdatamodeld/DateCounter.xcdatamodel/contents
> +        <attribute name="id" optional="YES" attributeType="UUID" usesScalarValueType="NO"/>
Vamos marcar apenas a data como obrigatória e deixar o resto como está

2022-11-20 13:36 UTC, antoniogermano commented on DateCounter/Views/DetailView.swift
> +    private var toolbarContent: ToolbarItem<(), Button<Label<Text, Image>>> {
```
.toolbar {
    editToolbarItem
    deleteToolbarItem
}
```
```
private var deleteToolbarItem: ToolbarItem<(), Button<Label<Text, Image>>> {
    ToolbarItem(placement: .destructiveAction) {
        Button {
            showDeleteAlert = true
        } label: {
            Label("Delete this event", systemImage: "trash")
        }
    }
}
```

2022-11-21 00:03 UTC, antoniogermano commented on DateCounter/Views/ContentView.swift
> +            components = DateComponents(nanosecond: 1) //FIXME: that's not supposed to happen
Será corrigido na #60

2022-11-21 00:07 UTC, antoniogermano approved these changes

2022-11-21 00:21 UTC, merged